# Automatically generated by TopicTreeSpecPrinter(**kwargs).
# The kwargs were:
# - fileObj: TextIOWrapper
# - footer: '# End of topic tree definition. Note that application may l...'
# - indentStep: 4
# - treeDoc: None
# - width: 70


class engine:
    """
    UNDOCUMENTED: created as parent without specification
    """

    class answer_status:
        """
        UNDOCUMENTED: created without spec
        """
        
        def msgDataSpec(status, fired, total, eta):
            """
            - eta: UNDOCUMENTED
            - fired: UNDOCUMENTED
            - status: UNDOCUMENTED
            - total: UNDOCUMENTED
            """

    class started:
        """
        UNDOCUMENTED: created without spec
        """
        
        def msgDataSpec(start, end):
            """
            - end: UNDOCUMENTED
            - start: UNDOCUMENTED
            """

    class status:
        """
        UNDOCUMENTED: created without spec
        """
        
        def msgDataSpec(text):
            """
            - text: UNDOCUMENTED
            """

    class stopped:
        """
        UNDOCUMENTED: created without spec
        """
        
        def msgDataSpec(stop):
            """
            - stop: UNDOCUMENTED
            """

class gui:
    """
    UNDOCUMENTED: created as parent without specification
    """

    class con:
        """
        UNDOCUMENTED: created as parent without specification
        """

        class connect:
            """
            UNDOCUMENTED: created without spec
            """
            
            def msgDataSpec(port=None):
                """
                - port: UNDOCUMENTED
                """

        class disconnect:
            """
            UNDOCUMENTED: created without spec
            """

    class laser:
        """
        UNDOCUMENTED: created as parent without specification
        """

        class cont:
            """
            UNDOCUMENTED: created without spec
            """

        class pause:
            """
            UNDOCUMENTED: created without spec
            """

        class start:
            """
            UNDOCUMENTED: created without spec
            """
            
            def msgDataSpec(pulse_count, frequency):
                """
                - frequency: UNDOCUMENTED
                - pulse_count: UNDOCUMENTED
                """

        class stop:
            """
            UNDOCUMENTED: created without spec
            """

    class request_status:
        """
        UNDOCUMENTED: created without spec
        """


# End of topic tree definition. Note that application may load
# more than one definitions provider.
